config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :work_activity_notifications, only: [:index, :show]

  mount HealthMonitor::Engine, at: "/"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  # This route is to handle user ids that are in the form abc@something.com because
  # Rails (understandably) does not like the ".com" in the URL
  get "users/:id.:format/edit", to: "users#edit"

  resources :users, except: [:new, :destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  # Per https://github.com/pulibrary/pul-the-hard-way/blob/main/services/cas.md
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "about", to: "welcome#about", as: :welcome_about
  get "license", to: "welcome#license", as: :welcome_license
  get "help", to: "welcome#help", as: :help

  # The wizard new submission controller (work wizard step 0)
  get "works/:id/new-submission", to: "works_wizard_new_submission#new_submission", as: :work_create_new_submission
  patch "works/:id/new-submission", to: "works_wizard_new_submission#new_submission_save", as: :work_new_submission
  get "works/:id/new-submission-delete", to: "works_wizard_new_submission#new_submission_delete", as: :work_delete_new_submission

  # The work wizard
  get "works/:id/readme-select", to: "works_wizard#readme_select", as: :work_readme_select
  patch "works/:id/readme-uploaded", to: "works_wizard#readme_uploaded", as: :work_readme_uploaded
  post "works/:id/readme-uploaded-payload", to: "works_wizard#readme_uploaded_payload", as: :work_readme_uploaded_payload
  patch "works/:id/file-upload", to: "works_wizard#file_uploaded", as: :work_file_uploaded
  get "works/:id/file-upload", to: "works_wizard#file_upload", as: :work_file_upload
  patch "works/:id/update-wizard", to: "works_wizard#update_wizard", as: :update_work_wizard
  get "works/:id/edit-wizard", to: "works_wizard#edit_wizard", as: :edit_work_wizard
  get "works/:id/file-other", to: "works_wizard#file_other", as: :work_file_other
  get "works/:id/review", to: "works_wizard#review", as: :work_review
  post "works/:id/review", to: "works_wizard#review"
  patch "works/:id/review", to: "works_wizard#review"
  post "works/:id/validate-wizard", to: "works_wizard#validate", as: :work_validate_wizard
  patch "works/:id/validate-wizard", to: "works_wizard#validate"
  post "works/:id/validate", to: "works#validate", as: :work_validate
  get "works/:id/attachment-select", to: "works_wizard#attachment_select", as: :work_attachment_select
  post "works/:id/attachment-select", to: "works_wizard#attachment_selected", as: :work_attachment_selected
  patch "works/:id/attachment-select", to: "works_wizard#attachment_selected"
  post "works/:id/upload-files-wizard", to: "works_wizard#upload_files", as: :work_wizard_upload_files

  get "works/:id/update-additional", to: "works_wizard_update_additional#update_additional", as: :work_update_additional
  patch "works/:id/update-additional", to: "works_wizard_update_additional#update_additional_save"

  # policy agreement
  get "works/policy", to: "works_wizard_policy#show", as: :work_policy
  post "works/policy", to: "works_wizard_policy#update"

  # policy agreement
  get "works/:id/complete", to: "works_wizard_submission_complete#show", as: :work_complete

  get "works/:id/file-list", to: "works#file_list", as: :work_file_list
  post "work/:id/approve", to: "works#approve", as: :approve_work
  post "work/:id/withdraw", to: "works#withdraw", as: :withdraw_work
  post "work/:id/resubmit", to: "works#resubmit", as: :resubmit_work
  post "work/:id/revert-to-draft", to: "works#revert_to_draft", as: :revert_work
  post "work/:id/add-message", to: "works#add_message", as: :add_message_work
  post "work/:id/add-provenance-note", to: "works#add_provenance_note", as: :add_provenance_note
  put "works/:id/assign-curator/:uid", to: "works#assign_curator", as: :work_assign_curator
  get "works/:id/datacite", to: "works#datacite", as: :datacite_work
  get "works/:id/datacite/validate", to: "works#datacite_validate", as: :datacite_validate_work
  get "works/:id/download", controller: "work_downloader", action: "download", as: :work_download
  post "works/:id/migrate_content", controller: "work_migration", action: "migrate", as: :work_migrate_content
  get "works/:id/bibtex" => "works#bibtex", as: :work_bibtex
  resources :works
  get "/doi/*doi", to: "works#resolve_doi", as: :resolve_doi, format: false
  get "/ark/*ark", to: "works#resolve_ark", as: :resolve_ark, format: false
  post "works/:id/upload-files", to: "works#upload_files", as: :work_upload_files

  get "upload-snapshots/:work_id", to: "upload_snapshots#edit", as: :edit_upload_snapshot
  get "upload-snapshots/:id/download", to: "upload_snapshots#download", as: :download_upload_snapshot
  post "upload-snapshots", to: "upload_snapshots#create", as: :create_upload_snapshot
  delete "upload-snapshots/:id", to: "upload_snapshots#destroy", as: :delete_upload_snapshot

  delete "groups/:id/:uid", to: "groups#delete_user_from_group", as: :delete_user_from_group
  post "groups/:id/add-submitter/:uid", to: "groups#add_submitter", as: :add_submitter
  post "groups/:id/add-admin/:uid", to: "groups#add_admin", as: :add_admin
  resources :groups

  get "/collections/:id", to: redirect("/groups/%{id}"), as: :collections
  get "/reports/dataset-list", to: "reports#dataset_list", as: :reports_dataset_list

  # researchers
  get "/researchers/ajax-list", to: "researchers#ajax_list", as: :researchers_ajax_list
  resources :researchers

  # Anything still unmatched by the end of the routes file should go to the not_found page
  # match '*a', to: redirect('/404'), via: :get

  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :error
end

app/models/group.rb
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
class Group < ApplicationRecord
  resourcify

  # GroupOptions model extensible options set for Groups and Users
  has_many :group_options, dependent: :destroy, class_name: "GroupOption"
  has_many :group_messaging_options, -> { where(option_type: GroupOption::EMAIL_MESSAGES) }, class_name: "GroupOption", dependent: :destroy

  has_many :users_with_options, through: :group_options, source: :user
  has_many :users_with_messaging, through: :group_messaging_options, source: :user

  validate do |group|
    if group.title.blank?
      group.errors.add :base, "Title cannot be empty"
    end
  end

  def default_admins_list
    return [] if code.blank?
    key = code.downcase.to_sym
    Rails.configuration.group_defaults.dig(key, :admin) || []
  end

  def default_submitters_list
    key = code.downcase.to_sym
    Rails.configuration.group_defaults.dig(key, :submit) || []
  end

  def super_administrators
    User.with_role(:super_admin)
  end

  def datasets
    Work.where(group_id: id)
  end

  def submitters
    User.with_role(:submitter, self)
  end

  # Permit a User to receive notification messages for members of this Group
  # @param user [User]
  def enable_messages_for(user:, subcommunity: nil)
    raise(ArgumentError, "User #{user.uid} is not an administrator or submitter for this group #{title}") unless user.can_admin?(self) || user.can_submit?(self)
    group = GroupOption.find_or_initialize_by(option_type: GroupOption::EMAIL_MESSAGES, user:, group: self, subcommunity:)
    group.enabled = true
    group.save
  end

  # Disable a User from receiving notification messages for members of this Group
  # @param user [User]
  def disable_messages_for(user:, subcommunity: nil)
    raise(ArgumentError, "User #{user.uid} is not an administrator or submitter for this group #{title}") unless user.can_admin?(self) || user.can_submit?(self)
    group = GroupOption.find_or_initialize_by(option_type: GroupOption::EMAIL_MESSAGES, user:, group: self, subcommunity:)
    group.enabled = false
    group.save
  end

  # Returns true if a given user has notification e-mails enabled for this Group
  # @param user [User]
  # @return [Boolean]
  def messages_enabled_for?(user:, subcommunity: nil)
    group_option = group_messaging_options.find_by(user:, group: self, subcommunity:)
    group_option ||= GroupOption.new(enabled: true)
    group_option.enabled
  end

  def self.create_defaults
    return if where(code: "RD").count > 0
    Rails.logger.info "Creating default Groups"
    create(title: "Princeton Research Data Service (PRDS)", code: "RD")
    create(title: "Princeton Plasma Physics Lab (PPPL)", code: "PPPL")
  end

  # Returns the default group.
  # Used when we don't have anything else to determine a more specific Group for a user.
  def self.default
    create_defaults
    research_data
  end

  # Returns the default group for a given department number.
  # Reference: https://docs.google.com/spreadsheets/d/1_Elxs3Ex-2wCbbKUzD4ii3k16zx36sYf/edit#gid=1484576831
  def self.default_for_department(department_number)
    if department_number.present? && department_number >= "31000" && department_number <= "31027"
      plasma_laboratory
    else
      default
    end
  end

  def self.research_data
    create_defaults
    where(code: "RD").first
  end

  def self.plasma_laboratory
    create_defaults
    where(code: "PPPL").first
  end

  def administrators
    User.with_role(:group_admin, self)
  end

  ##
  # The current user adds a new admin user to a group.
  # For use in the UI - we need to check whether the current_user
  # has the right permissions to add someone as an admin_user.
  # @param [User] current_user - the currently logged in user
  # @param [User] admin_user - the user who will be granted admin rights on this group
  def add_administrator(current_user, admin_user)
    if current_user.has_role?(:super_admin) || current_user.has_role?(:group_admin, self)
      if admin_user.has_role? :group_admin, self
        errors.add(:admin, "User has already been added")
      else
        errors.delete(:admin)
        admin_user.add_role :group_admin, self
      end
    else
      errors.add(:admin, "Unauthorized")
    end
  end

  def add_submitter(current_user, additional_user)
    if current_user.has_role?(:super_admin) || current_user.has_role?(:group_admin, self)
      return if (self == additional_user.default_group) && additional_user.just_created

      if additional_user.has_role? :submitter, self
        errors.add(:submitter, "User has already been added")
      else
        errors.delete(:submitter)
        additional_user.add_role :submitter, self
      end
    else
      errors.add(:submitter, "Unauthorized")
    end
  end

  # @param [User] current_user - the currently logged in user
  # @param [User] admin_user - the user who will be granted admin rights on this group
  # @param [String] role to be deleted
  def delete_permission(current_user, removed_user, role)
    if current_user.has_role?(:super_admin) || current_user.has_role?(:group_admin, self)
      if removed_user.nil?
        errors.add(:delete_permission, "User was not found")
      elsif removed_user == current_user
        errors.add(:delete_permission, "Cannot remove yourself from a group. Contact a super-admin for help.")
      else
        errors.delete(:delete_permission)
        removed_user.remove_role role, self
      end
    else
      errors.add(:delete_permission, "Unauthorized")
    end
  end

  def communities
    if code == "PPPL"
      ["Princeton Plasma Physics Laboratory"]
    else
      ["Princeton Neuroscience Institute", "Geosciences", "Mechanical and Aerospace Engineering",
       "Astrophysical Sciences", "Civil and Environmental Engineering", "Chemical and Biological Engineering",
       "Digital Humanities", "Music and Arts", "Princeton School of Public and International Affairs",
       "Chemistry", "Lewis-Sigler Institute of Integrative Genomics", "Architecture", "Ecology and Evolutionary Biology",
       "Economics", "Computational Social Science", "Electrical and Computer Engineering",
       "Geophysical Fluid Dynamics Laboratory", "Industrial Relations Section", "Molecular Biology", "Physics",
       "Psychology", "Sociology"].sort
    end
  end

  # rubocop:disable Metrics/MethodLength
  def subcommunities
    values = []
    if code == "PPPL"
      values << "Spherical Torus"
      values << "Advanced Projects"
      values << "ITER and Tokamaks"
      values << "Theory"
      values << "NSTX-U"
      values << "NSTX"
      values << "Discovery Plasma Science"
      values << "Theory and Computation"
      values << "Stellarators"
      values << "PPPL Collaborations"
      values << "MAST-U"
      values << "Other Projects"
      values << "System Studies"
      values << "Applied Materials and Sustainability Sciences"
      values << "Computational Science"
      values << "DIII-D"
      values << "Tokamak Experimental Sciences"

    end
    values.sort
  end
  # rubocop:enable Metrics/MethodLength

  def publisher
    if code == "PPPL"
      "Princeton Plasma Physics Laboratory, Princeton University"
    else
      "Princeton University"
    end
  end

  def default_community
    return communities.first if code == "PPPL"
  end

  def default_user(uid)
    user = User.find_by(uid:)
    return user if user.present?
    User.new_for_uid(uid, id)
  end
end
# rubocop:enable Metrics/ClassLength

app/controllers/groups_controller.rb
# frozen_string_literal: true
class GroupsController < ApplicationController
  def index; end

  def show
    @group = Group.find(params[:id])
    @can_edit = can_edit?
  end

  def edit
    @group = Group.find(params[:id])
    if can_edit?
      render "edit"
    else
      Rails.logger.warn("Unauthorized to edit group #{@group.id} (current user: #{current_user.id})")
      redirect_to groups_path
    end
  end

  # rubocop:disable Metrics/MethodLength
  def update
    @group = Group.find(params[:id])
    if can_edit?
      respond_to do |format|
        if @group.update(group_params)
          format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
          format.json { render :show, status: :ok, location: @group }
        else
          # return 200 so the loadbalancer doesn't capture the error
          format.html { render :edit }
          format.json { render json: @group.errors }
        end
      end
    else
      Rails.logger.warn("Unauthorized to update group #{@group.id} (current user: #{current_user.id})")
      redirect_to groups_path
    end
  end
  # rubocop:enable Metrics/MethodLength

  # This is a JSON only endpoint
  def add_admin
    @group = Group.find(params[:id])
    @group.add_administrator(current_user, User.new_for_uid(params[:uid]))
    check_and_render
  end

  # This is a JSON only endpoint
  def add_submitter
    @group = Group.find(params[:id])
    user = @group.default_user(params[:uid])
    @group.add_submitter(current_user, user)
    check_and_render
  end

  # This is a JSON only endpoint
  def delete_user_from_group
    @group = Group.find(params[:id])
    role = params[:role] || "submitter"
    @group.delete_permission(current_user, User.find_by(uid: params[:uid]), role)
    check_and_render
  end

  private

    def check_and_render
      if @group.errors.count > 0 && @group.errors.first.message == "Unauthorized"
        render status: :unauthorized, json: { message: "Unauthorized" }
      elsif @group.errors.count > 0
        render status: :bad_request, json: { message: @group.errors.first.message }
      else
        render status: :ok, json: { message: "OK" }
      end
    end

    # Only allow trusted parameters through.
    def group_params
      params.require(:group).permit([:title, :description])
    end

    def can_edit?
      current_user.can_admin? @group
    end
end

app/views/groups/_dataset_table.html.erb
<div class="dataset-table">
  <table id="<%= table_id %>" class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Name</th>
        <th>Curator</th>
        <th>Status</th>
        <th>Last Edited</th>
      </tr>
    </thead>
    <tbody>
      <% datasets.each do |ds| %>
        <tr>
          <td>
            <a href="<%= work_path(ds) %>"><%= ds.title %></a>
            <% if ds.new_notification_count_for_user(current_user.id) > 0 %>
              <a href="<%= work_path(ds) %>">
                <span class="badge rounded-pill bg-primary" title="<%= ds.new_notification_count_for_user(current_user.id) %> new notifications"><%= ds.new_notification_count_for_user(current_user.id) %></span>
              </a>
            <% end %>
          </td>
          <td><%= ds.created_by_user.uid %></td>
          <td>
              <span title="<%= ds.curator&.given_name %>"><%= ds.curator&.uid %></span>
          </td>
          <td><%= ds.state %></td>
          <!-- see https://datatables.net/manual/data/orthogonal-data for sorting options -->
          <td class="last-edited" data-sort="<%= ds.updated_at %>">
            <span title="<%= ds.updated_at.localtime %>"><%= distance_of_time_in_words_to_now(ds.updated_at) %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/edit.html.erb
<h1><%= t('groups.form.heading') %></h1>

<%= form_with(model: @group) do |form| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
        <% @group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Code" %><br>
    <%= form.object.code %>
  </div>

  <div class="field">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %><br>
    <%= form.text_area :description, :rows => 4, :cols => 50 %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', @group, class: "btn btn-secondary" %>
  </div>
<% end %>

<h2>Submitters</h2>
<p>Users that are allowed to add new works to this group</p>
<ul id="submitter-list">
<% @group.submitters.each do |user| %>
  <!--
    Notice that we render the list of submitters and admins as hidden spans that are then
    picked up by the JavaScript on the page and turned into visible HTMLs with all the bells
    and whistles. This is so that we have a single way of rendering the data (both the user
    permissions already on the database *and* the user permissions added on the fly by an
    administrator).
  -->
  <span class="hidden submitter-data"
    data-uid="<%= user.uid %>"
    data-group-id="<%= @group.id %>"
    data-can-delete="<%= user.uid != current_user.uid %>"
    data-you="<%= user.uid == current_user.uid %>"></span>
<% end %>
</ul>

<div>
    <input id="submitter-uid-to-add" placeholder="netid"></input>
    <%= link_to "Add Submitter", "#", id: "btn-add-submitter", class: "btn btn-secondary" %>
    <span id="add-submitter-message"></span>
</div>

<h2 class="user-section-heading">Moderators</h2>
<p>Users that are allowed to approve submissions to this group</p>
<ul id="curator-list">
<% @group.administrators.each do |user| %>
  <span class="hidden curator-data"
    data-uid="<%= user.uid %>"
    data-group-id="<%= @group.id %>"
    data-can-delete="<%= user.uid != current_user.uid %>"
    data-you="<%= user.uid == current_user.uid %>"></span>
<% end %>
</ul>

<div>
    <input id="admin-uid-to-add" placeholder="netid"></input>
    <%= link_to "Add Moderator", "#", id: "btn-add-admin", class: "btn btn-secondary" %>
    <span id="add-admin-message"></span>
</div>

<h2 class="user-section-heading">System Administrators</h2>
<p>Users with global access to the system for administration purposes</p>
<ul id="sysadmin-list">
<% @group.super_administrators.each do |user| %>
  <span class="hidden sysadmin-data"
    data-uid="<%= user.uid %>"
    data-group-id="<%= @group.id %>"
    data-can-delete="false"
    data-super-admin="true"
    data-you="<%= user.uid == current_user.uid %>"></span>
<% end %>
</ul>

<input type="hidden" id="deleteUserFromGroupUrl" name="deleteUserFromGroupUrl" value="<%= delete_user_from_group_url(id: @group.id, uid: "uid-placeholder") %>" />
<input type="hidden" id="formAuthenticityToken" name="formAuthenticityToken" value="<%= form_authenticity_token %>" />
<input type="hidden" id="groupId" name="groupId" value="<%= @group.id %>" />
<input type="hidden" id="addSubmitterUrl" name="addSubmitterUrl" value="<%= add_submitter_url(id: @group.id, uid: "uid-placeholder") %>" />
<input type="hidden" id="addAdminUrl" name="addAdminUrl" value="<%=  add_admin_url(id: @group.id, uid: "uid-placeholder") %>" />
<input type="hidden" id="userPath" name="userPath" value="<%= user_path('user-placeholder') %>" />
<input type="hidden" id="groupId" name="groupId" value="<%= @group.id %>" />

app/views/groups/index.html.erb
<h1><%= t('groups.index.heading') %></h1>
<ul>
  <% Group.all.each do |group| %>
    <li><%= link_to(group.title, group_path(group)) %>
    <% if group.description.present? %>
      <p><%= group.description %></p>
    <% end %>
  <% end %>
</ul>

app/views/groups/show.html.erb
<style>
  .user-section-heading {
    margin-top: 20px;
  }
</style>

<div>
  <% if @can_edit %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary") %>
  <% end %>
  <%= link_to("View all groups", groups_path) %>
</div>

<h1><%= @group.title.strip %> </h1>
<% if @group.description.present? %>
  <p><%= @group.description %></p>
<% end %>

<p>
  Users that are allowed to approve submissions to this group:
  <%= @group.administrators.map { |user| link_to(user.given_name_safe, user_path(user.uid)) }.to_sentence.html_safe %>
</p>

<% if @can_edit %>
  <h2 class="dataset-section">Datasets</h2>
  <% if @group.datasets.count > 0 %>
    <%= render partial: "dataset_table", locals: {table_id: "group_datasets", datasets: @group.datasets} %>
  <% else %>
    <p>No datasets have been created for this group.</p>
  <% end %>
<% end %>

<script type="text/javascript">
  $(function() {
    // https://www.datatables.net/reference/option/
    //  order: [] preserves the order from the backend
    var dataset_options = {searching: false, paging: false, info: false, order: []};
    $('#group_datasets').DataTable(dataset_options);
  });
</script>