config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :work_activity_notifications, only: [:index, :show]

  mount HealthMonitor::Engine, at: "/"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  # This route is to handle user ids that are in the form abc@something.com because
  # Rails (understandably) does not like the ".com" in the URL
  get "users/:id.:format/edit", to: "users#edit"

  resources :users, except: [:new, :destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  # Per https://github.com/pulibrary/pul-the-hard-way/blob/main/services/cas.md
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "about", to: "welcome#about", as: :welcome_about
  get "license", to: "welcome#license", as: :welcome_license
  get "help", to: "welcome#help", as: :help

  # The wizard new submission controller (work wizard step 0)
  get "works/:id/new-submission", to: "works_wizard_new_submission#new_submission", as: :work_create_new_submission
  patch "works/:id/new-submission", to: "works_wizard_new_submission#new_submission_save", as: :work_new_submission
  get "works/:id/new-submission-delete", to: "works_wizard_new_submission#new_submission_delete", as: :work_delete_new_submission

  # The work wizard
  get "works/:id/readme-select", to: "works_wizard#readme_select", as: :work_readme_select
  patch "works/:id/readme-uploaded", to: "works_wizard#readme_uploaded", as: :work_readme_uploaded
  post "works/:id/readme-uploaded-payload", to: "works_wizard#readme_uploaded_payload", as: :work_readme_uploaded_payload
  patch "works/:id/file-upload", to: "works_wizard#file_uploaded", as: :work_file_uploaded
  get "works/:id/file-upload", to: "works_wizard#file_upload", as: :work_file_upload
  patch "works/:id/update-wizard", to: "works_wizard#update_wizard", as: :update_work_wizard
  get "works/:id/edit-wizard", to: "works_wizard#edit_wizard", as: :edit_work_wizard
  get "works/:id/file-other", to: "works_wizard#file_other", as: :work_file_other
  get "works/:id/review", to: "works_wizard#review", as: :work_review
  post "works/:id/review", to: "works_wizard#review"
  patch "works/:id/review", to: "works_wizard#review"
  post "works/:id/validate-wizard", to: "works_wizard#validate", as: :work_validate_wizard
  patch "works/:id/validate-wizard", to: "works_wizard#validate"
  post "works/:id/validate", to: "works#validate", as: :work_validate
  get "works/:id/attachment-select", to: "works_wizard#attachment_select", as: :work_attachment_select
  post "works/:id/attachment-select", to: "works_wizard#attachment_selected", as: :work_attachment_selected
  patch "works/:id/attachment-select", to: "works_wizard#attachment_selected"
  post "works/:id/upload-files-wizard", to: "works_wizard#upload_files", as: :work_wizard_upload_files

  get "works/:id/update-additional", to: "works_wizard_update_additional#update_additional", as: :work_update_additional
  patch "works/:id/update-additional", to: "works_wizard_update_additional#update_additional_save"

  # policy agreement
  get "works/policy", to: "works_wizard_policy#show", as: :work_policy
  post "works/policy", to: "works_wizard_policy#update"

  # policy agreement
  get "works/:id/complete", to: "works_wizard_submission_complete#show", as: :work_complete

  get "works/:id/file-list", to: "works#file_list", as: :work_file_list
  post "work/:id/approve", to: "works#approve", as: :approve_work
  post "work/:id/withdraw", to: "works#withdraw", as: :withdraw_work
  post "work/:id/resubmit", to: "works#resubmit", as: :resubmit_work
  post "work/:id/revert-to-draft", to: "works#revert_to_draft", as: :revert_work
  post "work/:id/add-message", to: "works#add_message", as: :add_message_work
  post "work/:id/add-provenance-note", to: "works#add_provenance_note", as: :add_provenance_note
  put "works/:id/assign-curator/:uid", to: "works#assign_curator", as: :work_assign_curator
  get "works/:id/datacite", to: "works#datacite", as: :datacite_work
  get "works/:id/datacite/validate", to: "works#datacite_validate", as: :datacite_validate_work
  get "works/:id/download", controller: "work_downloader", action: "download", as: :work_download
  post "works/:id/migrate_content", controller: "work_migration", action: "migrate", as: :work_migrate_content
  get "works/:id/bibtex" => "works#bibtex", as: :work_bibtex
  resources :works
  get "/doi/*doi", to: "works#resolve_doi", as: :resolve_doi, format: false
  get "/ark/*ark", to: "works#resolve_ark", as: :resolve_ark, format: false
  post "works/:id/upload-files", to: "works#upload_files", as: :work_upload_files

  get "upload-snapshots/:work_id", to: "upload_snapshots#edit", as: :edit_upload_snapshot
  get "upload-snapshots/:id/download", to: "upload_snapshots#download", as: :download_upload_snapshot
  post "upload-snapshots", to: "upload_snapshots#create", as: :create_upload_snapshot
  delete "upload-snapshots/:id", to: "upload_snapshots#destroy", as: :delete_upload_snapshot

  delete "groups/:id/:uid", to: "groups#delete_user_from_group", as: :delete_user_from_group
  post "groups/:id/add-submitter/:uid", to: "groups#add_submitter", as: :add_submitter
  post "groups/:id/add-admin/:uid", to: "groups#add_admin", as: :add_admin
  resources :groups

  get "/collections/:id", to: redirect("/groups/%{id}"), as: :collections
  get "/reports/dataset-list", to: "reports#dataset_list", as: :reports_dataset_list

  # researchers
  get "/researchers/ajax-list", to: "researchers#ajax_list", as: :researchers_ajax_list
  resources :researchers

  # Anything still unmatched by the end of the routes file should go to the not_found page
  # match '*a', to: redirect('/404'), via: :get

  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :error
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def cas
    @user = User.from_cas(request.env["omniauth.auth"])
    if @user.nil?
      redirect_to root_path
      flash[:notice] = "You are not authorized"
    else
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      if is_navigational_format?
        if @user.default_group_id == Group.plasma_laboratory.id
          set_flash_message(:notice, :success, kind: "from Princeton Central Authentication Service")
        else
          flash[:notice] = "You are not a PPPL user."
        end
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  # Constants set by the <form> <input> parameters transmitted using POST/PATCH/PUT requests
  GROUP_MESSAGING_DISABLED = "0"
  GROUP_MESSAGING_ENABLED = "1"

  # Notice that `set_user` sets the value of the user that we are viewing or editing
  # while `authenticate_user` sets the value of the current logged in user.
  # These values can be different (e.g. when an admin users is editing the information
  # of another user)
  before_action :set_user, only: %i[show edit update]
  before_action :authenticate_user!

  def index
    @users = User.all.sort_by { |user| user.family_name || "" }
  end

  # GET /users/1
  def show
    @search_terms = params["q"].presence
    @can_edit = can_edit?
    @my_dashboard = current_user.id == @user.id
    render "forbidden", status: :forbidden if !current_user.super_admin? && !@my_dashboard

    @unfinished_works = WorkList.unfinished_works(@user, @search_terms)
    @completed_works = WorkList.completed_works(@user, @search_terms)
    @withdrawn_works = WorkList.withdrawn_works(@user, @search_terms)
    @works_found = @unfinished_works.length + @completed_works.length + @withdrawn_works.length
  end

  # GET /users/1/edit
  def edit
    unless can_edit?
      Rails.logger.warn("Unauthorized to edit user #{@user.id} (current user: #{current_user.id})")
      redirect_to user_path(@user)
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if can_edit?
      respond_to do |format|
        update_groups_with_messaging if user_params.key?(:groups_with_messaging)

        if @user.update(user_params)
          format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          # return 200 so the loadbalancer doesn't capture the error
          format.html { render :edit }
          format.json { render json: @user.errors }
        end
      end
    else
      Rails.logger.warn("Unauthorized to update user #{@user.id} (current user: #{current_user.id})")
      redirect_to user_path(@user)
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      user_id = user_id_from_url
      @user = User.friendly.find(user_id)
      redirect_to action: action_name, id: @user.friendly_id, status: :moved_permanently unless @user.friendly_id == user_id
    end

    def user_id_from_url
      # For external users UID is in the form `user-name@gmail.com`, however, Rails eats the ".com" from
      # the UID and dumps it into the `format` param. Here we make sure the ".com" is preserved when the
      # UID looks to be an external user id.
      external_uid = params[:id].include?("@")
      if external_uid && params["format"] == "com"
        "#{params[:id]}.#{params['format']}"
      else
        params[:id]
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      @user_params ||= params.require(:user).permit([
                                                      :given_name, :full_name, :family_name, :orcid, :email_messages_enabled,
                                                      :email, :default_group_id, groups_with_messaging: {}
                                                    ])
    end

    def can_edit?
      current_user.id == @user.id or current_user.super_admin?
    end

    def parameter_enables_messaging?(form_value)
      form_value.to_s == GROUP_MESSAGING_ENABLED
    end

    def update_groups_with_messaging
      if user_params.key?(:groups_with_messaging)
        extracted = user_params.extract!(:groups_with_messaging)
        groups_with_messaging = extracted[:groups_with_messaging]

        groups_with_messaging.each_pair do |id, param|
          group_id, subcommunity = id.split("_")
          selected_group = Group.find_by(id: group_id)

          if parameter_enables_messaging?(param)
            selected_group.enable_messages_for(user: @user, subcommunity:)
          else
            selected_group.disable_messages_for(user: @user, subcommunity:)
          end
        end
      end
    end
end

app/views/users/_dataset_table.html.erb
<div class="dataset-table">
  <table id="<%= table_id %>" class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Name</th>
        <th>Curator</th>
        <th>Status</th>
        <th>Last Edited</th>
      </tr>
    </thead>
    <tbody>
      <% datasets.each do |ds| %>
        <tr>
          <td>
            <% if ds.title.blank? %>
              <a href="<%= work_create_new_submission_path(ds) %>">(untitled)</a>
            <% else %>
              <a href="<%= work_path(ds) %>"><%= ds.title %></a>
            <% end %>
            <% if ds.new_notification_count_for_user(@user.id) > 0 %>
              <a href="<%= work_path(ds) %>">
                <span class="badge rounded-pill bg-primary" title="<%= ds.new_notification_count_for_user(@user.id) %> new notifications"><%= ds.new_notification_count_for_user(@user.id) %></span>
              </a>
            <% end %>
          </td>
          <td><%= ds.created_by_user.uid %></td>
          <td>
              <span title="<%= ds.curator&.given_name %>"><%= ds.curator&.uid %></span>
          </td>
          <td><%= ds.state %></td>
          <!-- see https://datatables.net/manual/data/orthogonal-data for sorting options -->
          <td class="last-edited" data-sort="<%= ds.updated_at %>">
            <span title="<%= ds.updated_at.localtime %>"><%= distance_of_time_in_words_to_now(ds.updated_at) %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<% if current_user.id == @user.id %>
  <section class="card message-settings">
    <%= form_with(model: @user, class: ["form", "container"]) do |form| %>
      <fieldset>
        <legend><%= t("users.form.email_messages") %></legend>
        <div class="form-check ">
          <%= form.check_box(:email_messages_enabled, class: ["form-check-input","form-email-all"]) %>
          <%= label_tag(:email_messages_enabled, t("users.form.email_messages_enabled"), class: ["form-check-label"]) %>
        </div>
      </fieldset>

      <section class="card container groups">
        <h2><%= t('users.form.group') %></h2>
        <fieldset>
          <% @user.submitter_or_admin_groups.each do |group| %>
            <legend><%= group.title %></legend>
            <div class="form-check">
              <%= hidden_field_tag "user[groups_with_messaging][#{group.id}]", 0, { id: "group_messaging_#{group.id}" } %>
              <%= check_box_tag("user[groups_with_messaging][#{group.id}]", { id: "group_messaging_#{group.id}", checked: group.messages_enabled_for?(user: user), class: ["form-check-input", "form-group-check"] }) %>
              <%= label("user[groups_with_messaging][#{group.id}]", t("users.form.email_messages_enabled"), class: ["form-check-label"]) %>

              <div class="form-subcommunities">
              <% group.subcommunities.each do |subcommunity| %>
                <div class="form-check">
                  <%= hidden_field_tag "user[groups_with_messaging][#{group.id}_#{subcommunity}]", 0, { id: "group_messaging_#{group.id}_#{subcommunity}" } %>
                  <%= check_box_tag("user[groups_with_messaging][#{group.id}_#{subcommunity}]", { id: "group_messaging_#{group.id}_#{subcommunity}", checked: group.messages_enabled_for?(user: user, subcommunity: subcommunity), class: ["form-check-input", "form-subcommunity-check"] }) %>
                  <%= label("user[groups_with_messaging][#{group.id}_#{subcommunity}]", subcommunity, class: ["form-check-label"]) %>
                </div>
              <% end %>
              </div>
            </div>
          <% end %>
        </fieldset>
      </section>

      <button type="submit" class="btn btn-primary"><%= t("users.form.email_messages_submit") %></button>
    <% end %>
  </section>
<% end %>

<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  Given name (First name)
  <br />
  <%= form.text_field :given_name %>
  </div>

  <div class="field">
    Family name (Last name)
    <br />
    <%= form.text_field :family_name %>
  </div>

  <div class="field">
  Full name
  <br />
  <%= form.text_field :full_name %>
  </div>

  <div class="field">
    ORCID iD
    <span id="orcid-bad" class="hidden text-muted field-hint"> - use format 0000-0000-0000-0000</span>
    <span id="orcid-ok" class="hidden"><img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" /></span>
    <br />
    <%= form.text_field :orcid, placeholder: "0000-0000-0000-0000" %>
  </div>

  <div class="field">
    Email<br />
    <%= form.text_field :email, class: "user-edit-long-field" %>
  </div>

  <div class="field">
    Princeton Net ID<br />
    <%= form.text_field :uid, class: "user-edit-long-field", readonly: true %>
  </div>

  <% if current_user.moderator? || current_user.super_admin? %>
    <div class="field">
      Default group<br />
      <%= form.collection_select :default_group_id, Group.order(:title), :id, :title, {include_blank: false}, {class: "user-edit-long-field"} %>
    </div>
  <% else %>
    <div class="field">
      Default group<br />
      <input type="text" class="user-edit-long-field" readonly value="<%= @user.default_group.title %>" />
    </div>
  <% end %>

  <div class="text-left">
    <%= form.submit "Save", class: "btn btn-primary" %>
    <%= link_to 'Cancel', @user, :class => "btn btn-secondary", :role => "button" %>
  </div>
<% end %>

<script>

$(function() {
  var validateOrcid = function() {
    var value = $("#user_orcid").val().trim();
    if (value == "") {
      $("#orcid-bad").addClass("hidden");
      $("#orcid-ok").addClass("hidden");
      return;
    }

    if (isOrcid(value)) {
      $("#orcid-bad").addClass("hidden");
      $("#orcid-ok").removeClass("hidden");
    } else {
      $("#orcid-bad").removeClass("hidden");
      $("#orcid-ok").addClass("hidden");
    }
  }

  $("#user_orcid").on("input", function() { validateOrcid(); });
  validateOrcid();
});

</script>

app/views/users/edit.html.erb
<h1>My Profile Settings</h1>
<%= render 'form', user: @user %>

app/views/users/forbidden.html.erb
<h2>Forbidden</h2>

<p>Your account is not authorized to access the dashboard for this user.</p>

app/views/users/index.html.erb
<h1>Users</h1>

<table id="user-list-table">
  <thead>
    <tr class="user-list-header-row">
      <th>Net ID</th>
      <th>Given name</th>
      <th>Family name</th>
      <th>Full name</th>
      <th>ORCID</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr class="user-list-data-row">
      <td>
        <%= link_to(user.uid, user_path(user)) %>
        <% if user.uid == current_user.uid %>
          &nbsp;(you)
        <% end %>
      </td>

      <td><%= user.given_name_safe %></td>
      <td><%= user.family_name %></td>
      <td><%= user.full_name %></td>
      <td><%= user.orcid %></td>
    </tr>
    <% end %>
</tbody>
</table>

app/views/users/show.html.erb
<div class="search-bar">
  <div class="search-form">
    <%= form_with(url: user_path(@user.uid), method: "get") do %>
      <%= text_field_tag(:q, @search_terms, {placeholder: "Search by DOI, Title, Name, ARK"}) %>
      <%= submit_tag("Search", class: "btn btn-primary") %>
    <% end %>
  </div>
</div>

<h2>
  <%= @my_dashboard ? "Welcome " : "" %><%= @user.given_name_safe %>
  <% if @user.super_admin? %>
    <span class="badge rounded-pill bg-primary text-bg-secondary">Administrator</span>
  <% elsif @user.moderator? %>
    <span class="badge rounded-pill bg-primary text-bg-secondary">Moderator</span>
  <% end %>
</h2>

<% if @user.pending_notifications_count > 0 %>
  <p>You have <%= @user.pending_notifications_count %> new messages.</p>
<% end %>

<% if @my_dashboard && @user.orcid.blank? %>
  <p>
    You do not have an  ORCID iD on file. <%= link_to("Add one", edit_user_path(@user)) %> to your profile.
  </p>
  <p>
    ORCID, Open Research and Contributor ID, is a non-profit organization that promotes the use of
    a unique digital identifier in an effort to help link researchers to their scholarly works
    regardless of institutional affiliation, moves or names. You can learn more about ORCID in
    our <a target="_blank" href="https://researchdata.princeton.edu/research-lifecycle-guide/orcid">ORCID guide</a>
    and register for one at <a target="_blank" href="https://orcid.org/register">https://orcid.org/register</a>.
  </p>
<% end %>

<% if @user.super_admin? %>
  <!-- not sure we want to display the groups here, it's pointless -->
<% elsif @user.moderator? %>
  <p>Moderator for:
    <%= @user.admin_groups.map do |group|
      link_to(group.title, group_path(group))
    end.to_sentence.html_safe %></p>
<% end %>

<% if @my_dashboard %>
  <div class="text-left dashboard-options">
    <%= link_to t("users.form.create_work"), work_policy_path, class: "btn btn-primary", :role => "button", title: "Start the process to deposit a new dataset" %>
  </div>
<% else %>
  <% if @can_edit %>
    <div class="text-left dashboard-options">
      <%= link_to "Edit User", edit_user_path(@user), :class => "btn btn-primary", :role => "button" %>
    </div>
  <% end %>
<% end %>

<% if @unfinished_works.count > 0 %>
  <h2 class="dataset-section unfinished-submission"><%= pluralize(@unfinished_works.count, "Unfinished Submission")%></h2>
  <%= render partial: "dataset_table", locals: {table_id: "unfinished_datasets", datasets: @unfinished_works} %>
<% end %>

<% if @completed_works.count > 0 %>
  <h2 class="dataset-section completed-submission"><%= pluralize(@completed_works.count, "Completed Submission")%></h2>
  <%= render partial: "dataset_table", locals: {table_id: "completed_datasets", datasets: @completed_works} %>
<% end %>

<% if @withdrawn_works.count > 0 %>
  <h2 class="dataset-section">Withdrawn Submissions</h2>
  <%= render partial: "dataset_table", locals: {table_id: "withdrawn_datasets", datasets: @withdrawn_works} %>
<% end %>

<% if @works_found == 0 && @search_terms.present? %>
  <h2 class="dataset-section-no-works">No works found</h2>
  <p>No works found for <i><%= @search_terms %></i></p>
<% end %>

<script type="text/javascript">
  $(function() {
    // https://www.datatables.net/reference/option/
    //  order: [] preserves the order from the backend
    var dataset_options = {searching: false, paging: false, info: false, order: []};
    $('#unfinished_datasets').DataTable(dataset_options);
    $('#completed_datasets').DataTable(dataset_options);
    $('#withdrawn_datasets').DataTable(dataset_options);
  });
</script>