config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :work_activity_notifications, only: [:index, :show]

  mount HealthMonitor::Engine, at: "/"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  # This route is to handle user ids that are in the form abc@something.com because
  # Rails (understandably) does not like the ".com" in the URL
  get "users/:id.:format/edit", to: "users#edit"

  resources :users, except: [:new, :destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  # Per https://github.com/pulibrary/pul-the-hard-way/blob/main/services/cas.md
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "about", to: "welcome#about", as: :welcome_about
  get "license", to: "welcome#license", as: :welcome_license
  get "help", to: "welcome#help", as: :help

  # The wizard new submission controller (work wizard step 0)
  get "works/:id/new-submission", to: "works_wizard_new_submission#new_submission", as: :work_create_new_submission
  patch "works/:id/new-submission", to: "works_wizard_new_submission#new_submission_save", as: :work_new_submission
  get "works/:id/new-submission-delete", to: "works_wizard_new_submission#new_submission_delete", as: :work_delete_new_submission

  # The work wizard
  get "works/:id/readme-select", to: "works_wizard#readme_select", as: :work_readme_select
  patch "works/:id/readme-uploaded", to: "works_wizard#readme_uploaded", as: :work_readme_uploaded
  post "works/:id/readme-uploaded-payload", to: "works_wizard#readme_uploaded_payload", as: :work_readme_uploaded_payload
  patch "works/:id/file-upload", to: "works_wizard#file_uploaded", as: :work_file_uploaded
  get "works/:id/file-upload", to: "works_wizard#file_upload", as: :work_file_upload
  patch "works/:id/update-wizard", to: "works_wizard#update_wizard", as: :update_work_wizard
  get "works/:id/edit-wizard", to: "works_wizard#edit_wizard", as: :edit_work_wizard
  get "works/:id/file-other", to: "works_wizard#file_other", as: :work_file_other
  get "works/:id/review", to: "works_wizard#review", as: :work_review
  post "works/:id/review", to: "works_wizard#review"
  patch "works/:id/review", to: "works_wizard#review"
  post "works/:id/validate-wizard", to: "works_wizard#validate", as: :work_validate_wizard
  patch "works/:id/validate-wizard", to: "works_wizard#validate"
  post "works/:id/validate", to: "works#validate", as: :work_validate
  get "works/:id/attachment-select", to: "works_wizard#attachment_select", as: :work_attachment_select
  post "works/:id/attachment-select", to: "works_wizard#attachment_selected", as: :work_attachment_selected
  patch "works/:id/attachment-select", to: "works_wizard#attachment_selected"
  post "works/:id/upload-files-wizard", to: "works_wizard#upload_files", as: :work_wizard_upload_files

  get "works/:id/update-additional", to: "works_wizard_update_additional#update_additional", as: :work_update_additional
  patch "works/:id/update-additional", to: "works_wizard_update_additional#update_additional_save"

  # policy agreement
  get "works/policy", to: "works_wizard_policy#show", as: :work_policy
  post "works/policy", to: "works_wizard_policy#update"

  # policy agreement
  get "works/:id/complete", to: "works_wizard_submission_complete#show", as: :work_complete

  get "works/:id/file-list", to: "works#file_list", as: :work_file_list
  post "work/:id/approve", to: "works#approve", as: :approve_work
  post "work/:id/withdraw", to: "works#withdraw", as: :withdraw_work
  post "work/:id/resubmit", to: "works#resubmit", as: :resubmit_work
  post "work/:id/revert-to-draft", to: "works#revert_to_draft", as: :revert_work
  post "work/:id/add-message", to: "works#add_message", as: :add_message_work
  post "work/:id/add-provenance-note", to: "works#add_provenance_note", as: :add_provenance_note
  put "works/:id/assign-curator/:uid", to: "works#assign_curator", as: :work_assign_curator
  get "works/:id/datacite", to: "works#datacite", as: :datacite_work
  get "works/:id/datacite/validate", to: "works#datacite_validate", as: :datacite_validate_work
  get "works/:id/download", controller: "work_downloader", action: "download", as: :work_download
  post "works/:id/migrate_content", controller: "work_migration", action: "migrate", as: :work_migrate_content
  get "works/:id/bibtex" => "works#bibtex", as: :work_bibtex
  resources :works
  get "/doi/*doi", to: "works#resolve_doi", as: :resolve_doi, format: false
  get "/ark/*ark", to: "works#resolve_ark", as: :resolve_ark, format: false
  post "works/:id/upload-files", to: "works#upload_files", as: :work_upload_files

  get "upload-snapshots/:work_id", to: "upload_snapshots#edit", as: :edit_upload_snapshot
  get "upload-snapshots/:id/download", to: "upload_snapshots#download", as: :download_upload_snapshot
  post "upload-snapshots", to: "upload_snapshots#create", as: :create_upload_snapshot
  delete "upload-snapshots/:id", to: "upload_snapshots#destroy", as: :delete_upload_snapshot

  delete "groups/:id/:uid", to: "groups#delete_user_from_group", as: :delete_user_from_group
  post "groups/:id/add-submitter/:uid", to: "groups#add_submitter", as: :add_submitter
  post "groups/:id/add-admin/:uid", to: "groups#add_admin", as: :add_admin
  resources :groups

  get "/collections/:id", to: redirect("/groups/%{id}"), as: :collections
  get "/reports/dataset-list", to: "reports#dataset_list", as: :reports_dataset_list

  # researchers
  get "/researchers/ajax-list", to: "researchers#ajax_list", as: :researchers_ajax_list
  resources :researchers

  # Anything still unmatched by the end of the routes file should go to the not_found page
  # match '*a', to: redirect('/404'), via: :get

  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :error
end

app/views/shared/_admin_actions.html.erb
<nav id="admin-actions" class="col-sm" role="menu">
  <%= link_to "Groups","#{root_url}groups", :role => "menuitem", :class => "btn btn-primary groups" %>
</nav>

app/views/shared/_footer.html.erb
<hr />
<div>
  <div class="deployment-version" >
    <text-style variation="strong">
      Version:
      <% @version = VersionFooter.info %>
      <% if @version[:error] %>
        <%= @version[:error] %>
      <% else %>
        <% if @version[:stale] %>
          (stale)
        <% end %>
        <span title="<%= @version[:sha] %>">
          <% if @version[:tagged_release] %>
            <a href="https://github.com/pulibrary/pdc_describe/releases/tag/<%= @version[:branch] %>" target="_blank"><%= @version[:branch] %></a>
          <% else %>
            <%= @version[:branch] %>,
          <% end %>
          last updated: <%= @version[:version] %>
        </span>
     <% end %>
    </text-style>
  </div>
  <div id="footer">
    <div class="content">
      <div class= "pul-accessible">
        <%= link_to("Accessibility","https://accessibility.princeton.edu/help", target:"blank") %>
      </div>
      <%= link_to(image_tag("pul_logo_0.png", alt: "Princeton University Library"), "https://library.princeton.edu", target: "blank") %>
      <%= link_to(image_tag("footer_logo.png", alt: "Princeton Research Data Service"), "https://researchdata.princeton.edu", target: "blank") %>
      <%= link_to(image_tag("princeton_research_logo_2.png", alt: "Office for the Dean of Research"), "https://research.princeton.edu", target: "blank") %>
      <%= link_to(image_tag("princeton_logo.png", alt: "Princeton University"), "https://www.princeton.edu", target: "blank") %>
    </div>
  </div>
  <div id="copyright">
    &copy; <%= Date.current.year %> The Trustees of Princeton University
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="p-5 text-left bg-light">
    <%= link_to "PDC Describe", root_path, class: 'navbar-logo' %>
    <div class="menu">
      <% if current_user && (current_user.super_admin? || current_user.moderator?) %>
        <%= render 'shared/admin_actions' %>
      <% end %>
      <% if current_user %>
        <nav id="menu" class="col-sm" role="menu">
          <%= link_to "How to Submit", "#{root_url}#how-to-submit", :class => "btn btn-primary how-to-submit", :role => "menuitem" %>
          <%= link_to "Need Help?", "#{root_url}help", :class =>"btn btn-secondary help", :role => "menuitem" %>
        </nav>
      <% else %>
        <div id="pdc-discovery-label">Looking for data? Go to</div>
        <nav id="menu" class="col-sm" role="menu">
          <%= link_to "Princeton Data Commons: Discovery","https://datacommons.princeton.edu/discovery/", :class => "btn btn-primary about", :role => "menuitem" %>
          <%= link_to "How to Submit", "#{root_url}#how-to-submit", :class => "btn btn-primary how-to-submit", :role => "menuitem" %>
          <%= link_to "Need Help?", "#{root_url}help", :class =>"btn btn-secondary help", :role => "menuitem" %>
        </nav>
      <% end %>
      <nav id="user-actions" class="col-sm">
        <% if current_user %>
        <%= render 'shared/user_actions' %>
        <% else %>
        <%= button_to "Log In", user_cas_omniauth_authorize_path, class: "btn btn-primary log-in", style: "background-color: #3f76ca" %>
        <% end %>
      </nav>
    </div>

  </div>
</header>

app/views/shared/_user_actions.html.erb
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle current-user" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= current_user.uid %>
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" role="menu">
    <%= link_to "My Dashboard", user_path(current_user), class: "dropdown-item my-dashboard", role: "menuitem" %>
    <%= link_to "My Profile", edit_user_path(current_user), class: "dropdown-item my-profile", role: "menuitem" %>
    <% if current_user.moderator? %>
      <%= link_to "Create Dataset", new_work_path, class: "dropdown-item", role: "menuitem" %>
      <% if current_user.can_admin?(Group.research_data) %>
        <%= link_to "Migrate PRDS Dataset", new_work_path(migrate: true, group_code: Group.research_data.code), class: "dropdown-item", role: "menuitem" %>
      <% end %>
      <% if current_user.can_admin?(Group.plasma_laboratory) %>
        <%= link_to "Migrate PPPL Dataset", new_work_path(migrate: true, group_code: Group.plasma_laboratory.code), class: "dropdown-item", role: "menuitem" %>
      <% end %>
    <% end %>
    <%= link_to "Notifications", work_activity_notifications_path, class: "dropdown-item my-profile", role: "menuitem" %>
    <%= link_to "Log Out", main_app.destroy_user_session_path, class: 'dropdown-item log-out', role: "menuitem" %>
  </div>
</div>