config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  resources :work_activity_notifications, only: [:index, :show]

  mount HealthMonitor::Engine, at: "/"

  authenticate :user, ->(user) { user.super_admin? } do
    mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app
  end

  # This route is to handle user ids that are in the form abc@something.com because
  # Rails (understandably) does not like the ".com" in the URL
  get "users/:id.:format/edit", to: "users#edit"

  resources :users, except: [:new, :destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#index"

  # Per https://github.com/pulibrary/pul-the-hard-way/blob/main/services/cas.md
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "about", to: "welcome#about", as: :welcome_about
  get "license", to: "welcome#license", as: :welcome_license
  get "help", to: "welcome#help", as: :help

  # The wizard new submission controller (work wizard step 0)
  get "works/:id/new-submission", to: "works_wizard_new_submission#new_submission", as: :work_create_new_submission
  patch "works/:id/new-submission", to: "works_wizard_new_submission#new_submission_save", as: :work_new_submission
  get "works/:id/new-submission-delete", to: "works_wizard_new_submission#new_submission_delete", as: :work_delete_new_submission

  # The work wizard
  get "works/:id/readme-select", to: "works_wizard#readme_select", as: :work_readme_select
  patch "works/:id/readme-uploaded", to: "works_wizard#readme_uploaded", as: :work_readme_uploaded
  post "works/:id/readme-uploaded-payload", to: "works_wizard#readme_uploaded_payload", as: :work_readme_uploaded_payload
  patch "works/:id/file-upload", to: "works_wizard#file_uploaded", as: :work_file_uploaded
  get "works/:id/file-upload", to: "works_wizard#file_upload", as: :work_file_upload
  patch "works/:id/update-wizard", to: "works_wizard#update_wizard", as: :update_work_wizard
  get "works/:id/edit-wizard", to: "works_wizard#edit_wizard", as: :edit_work_wizard
  get "works/:id/file-other", to: "works_wizard#file_other", as: :work_file_other
  get "works/:id/review", to: "works_wizard#review", as: :work_review
  post "works/:id/review", to: "works_wizard#review"
  patch "works/:id/review", to: "works_wizard#review"
  post "works/:id/validate-wizard", to: "works_wizard#validate", as: :work_validate_wizard
  patch "works/:id/validate-wizard", to: "works_wizard#validate"
  post "works/:id/validate", to: "works#validate", as: :work_validate
  get "works/:id/attachment-select", to: "works_wizard#attachment_select", as: :work_attachment_select
  post "works/:id/attachment-select", to: "works_wizard#attachment_selected", as: :work_attachment_selected
  patch "works/:id/attachment-select", to: "works_wizard#attachment_selected"
  post "works/:id/upload-files-wizard", to: "works_wizard#upload_files", as: :work_wizard_upload_files

  get "works/:id/update-additional", to: "works_wizard_update_additional#update_additional", as: :work_update_additional
  patch "works/:id/update-additional", to: "works_wizard_update_additional#update_additional_save"

  # policy agreement
  get "works/policy", to: "works_wizard_policy#show", as: :work_policy
  post "works/policy", to: "works_wizard_policy#update"

  # policy agreement
  get "works/:id/complete", to: "works_wizard_submission_complete#show", as: :work_complete

  get "works/:id/file-list", to: "works#file_list", as: :work_file_list
  post "work/:id/approve", to: "works#approve", as: :approve_work
  post "work/:id/withdraw", to: "works#withdraw", as: :withdraw_work
  post "work/:id/resubmit", to: "works#resubmit", as: :resubmit_work
  post "work/:id/revert-to-draft", to: "works#revert_to_draft", as: :revert_work
  post "work/:id/add-message", to: "works#add_message", as: :add_message_work
  post "work/:id/add-provenance-note", to: "works#add_provenance_note", as: :add_provenance_note
  put "works/:id/assign-curator/:uid", to: "works#assign_curator", as: :work_assign_curator
  get "works/:id/datacite", to: "works#datacite", as: :datacite_work
  get "works/:id/datacite/validate", to: "works#datacite_validate", as: :datacite_validate_work
  get "works/:id/download", controller: "work_downloader", action: "download", as: :work_download
  post "works/:id/migrate_content", controller: "work_migration", action: "migrate", as: :work_migrate_content
  get "works/:id/bibtex" => "works#bibtex", as: :work_bibtex
  resources :works
  get "/doi/*doi", to: "works#resolve_doi", as: :resolve_doi, format: false
  get "/ark/*ark", to: "works#resolve_ark", as: :resolve_ark, format: false
  post "works/:id/upload-files", to: "works#upload_files", as: :work_upload_files

  get "upload-snapshots/:work_id", to: "upload_snapshots#edit", as: :edit_upload_snapshot
  get "upload-snapshots/:id/download", to: "upload_snapshots#download", as: :download_upload_snapshot
  post "upload-snapshots", to: "upload_snapshots#create", as: :create_upload_snapshot
  delete "upload-snapshots/:id", to: "upload_snapshots#destroy", as: :delete_upload_snapshot

  delete "groups/:id/:uid", to: "groups#delete_user_from_group", as: :delete_user_from_group
  post "groups/:id/add-submitter/:uid", to: "groups#add_submitter", as: :add_submitter
  post "groups/:id/add-admin/:uid", to: "groups#add_admin", as: :add_admin
  resources :groups

  get "/collections/:id", to: redirect("/groups/%{id}"), as: :collections
  get "/reports/dataset-list", to: "reports#dataset_list", as: :reports_dataset_list

  # researchers
  get "/researchers/ajax-list", to: "researchers#ajax_list", as: :researchers_ajax_list
  resources :researchers

  # Anything still unmatched by the end of the routes file should go to the not_found page
  # match '*a', to: redirect('/404'), via: :get

  match "/404", to: "errors#not_found", via: :all, as: :not_found
  match "/500", to: "errors#internal_server_error", via: :all, as: :error
end

app/controllers/works_wizard_controller.rb
# frozen_string_literal: true

require "nokogiri"
require "open-uri"

# Controller to handle wizard Mode when editing an work
#
# The wizard flow is shown in the [mermaid diagram here](https://github.com/pulibrary/pdc_describe/blob/main/docs/wizard_flow.md).

class WorksWizardController < ApplicationController
  include ERB::Util
  around_action :rescue_aasm_error, only: [:validate, :new_submission_save]

  before_action :load_work, only: [:edit_wizard, :update_wizard, :attachment_select, :attachment_selected,
                                   :file_upload, :file_uploaded, :file_other, :review, :validate,
                                   :readme_select, :readme_uploaded, :readme_uploaded_payload]

  # GET /works/1/edit-wizard
  def edit_wizard
    @wizard_mode = true
    if validate_modification_permissions(work: @work,
                                         uneditable_message: "Can not edit work: #{@work.id} is not editable by #{current_user.uid}",
                                         current_state_message: "Can not edit work: #{@work.id} is not editable in current state by #{current_user.uid}")

      prepare_decorators_for_work_form(@work)
    end
  end

  # PATCH /works/1/update-wizard
  def update_wizard
    edit_helper(:edit_wizard, work_update_additional_path(@work))
  end

  # Prompt to select how to submit their files
  # GET /works/1/attachment_select
  def attachment_select; end

  # User selected a specific way to submit their files
  # POST /works/1/attachment_selected
  def attachment_selected
    @work.files_location = params["attachment_type"]
    @work.save!

    # create a directory for the work if the curator will need to move files by hand
    @work.s3_query_service.create_directory if @work.files_location != "file_upload"

    if params[:save_only] == "true"
      render :attachment_select
    else
      redirect_to file_location_url
    end
  end

  # Allow user to upload files directly
  # GET /works/1/file_upload
  def file_upload
    @work_decorator = WorkDecorator.new(@work, current_user)
  end

  # POST /works/1/upload-files-wizard (called via Uppy)
  def upload_files
    @work = Work.find(params[:id])
    upload_service = WorkUploadsEditService.new(@work, current_user)
    upload_service.update_precurated_file_list(params["files"], [])
    render plain: params["files"].map(&:original_filename).join(",")
  end

  # POST /works/1/file_upload
  def file_uploaded
    upload_service = WorkUploadsEditService.new(@work, current_user)
    # By the time we hit this endpoint files have been uploaded by Uppy submmitting POST requests
    # to /works/1/upload-files-wizard therefore we only need to delete files here and update the upload snapshot.
    @work = upload_service.snapshot_uppy_and_delete_files(deleted_files_param)

    prepare_decorators_for_work_form(@work)
    if params[:save_only] == "true"
      render :file_upload
    else
      redirect_to(work_review_path)
    end
  rescue => ex
    # Notice that we log the URL (rather than @work.doi) because sometimes we are getting a nil @work.
    # The URL will include the ID and might help us troubleshoot the issue further if it happens again.
    # See https://github.com/pulibrary/pdc_describe/issues/1801
    error_message = "Failed to update work snapshot, URL: #{request.url}: #{ex}"
    Rails.logger.error(error_message)
    Honeybadger.notify(error_message)
    flash[:notice] = "Failed to update work snapshot, work: #{@work&.doi}: #{ex}. Please contact rdss@princeton.edu for assistance."

    redirect_to work_file_upload_path(@work)
  end

  # Allow user to indicate where their files are located in the WWW
  # GET /works/1/file_other
  def file_other; end

  # GET /works/1/review
  # POST /works/1/review
  def review
    if request.method == "POST" || request.method == "PATCH"
      @work.location_notes = params["location_notes"]
      @work.save!
      if params[:save_only] == "true"
        render :file_other
      end
    end
  end

  # Validates that the work is ready to be approved
  # POST /works/1/validate-wizard
  # PATCH /works/1/validate-wizard
  def validate
    @work.submission_notes = params["submission_notes"]

    if params[:save_only] == "true"
      @work.save
      render :review
    else
      @work.complete_submission!(current_user)
      redirect_to work_complete_path(@work.id)
    end
  end

  # Show the user the form to select a readme
  # GET /works/1/readme_select
  def readme_select
    readme = Readme.new(@work, current_user)
    @readme = readme.file_name
  end

  # Hit when the user clicks "Save" or "Next" on the README upload process.
  # Notice that this does not really uploads the file, that happens in readme_uploaded_payload.
  # PATCH /works/1/readme_uploaded
  def readme_uploaded
    readme = Readme.new(@work, current_user)
    if params[:save_only] == "true"
      @readme = readme.file_name
      render :readme_select
    else
      redirect_to work_attachment_select_url(@work)
    end
  end

  def files_param
    params["files"]
  end

  # Uploads the README file, called by Uppy.
  # POST /works/1/readme-uploaded-payload
  def readme_uploaded_payload
    raise StandardError("Only one README file can be uploaded.") if files_param.empty?
    raise StandardError("Only one README file can be uploaded.") if files_param.length > 1

    readme_file = files_param.first
    readme = Readme.new(@work, current_user)

    readme_error = readme.attach(readme_file)
    if readme_error.nil?
      render plain: readme.file_name
    else
      # Tell Uppy there was an error uploading the README
      render plain: readme.file_name, status: :internal_server_error
    end
  end

  def file_location_url
    WorkMetadataService.file_location_url(@work)
  end
  helper_method :file_location_url

  private

    # rubocop:disable Metrics/MethodLength
    def edit_helper(view_name, redirect_url)
      if validate_modification_permissions(work: @work,
                                           uneditable_message: "Can not update work: #{@work.id} is not editable by #{current_user.uid}",
                                           current_state_message: "Can not update work: #{@work.id} is not editable in current state by #{current_user.uid}")
        prepare_decorators_for_work_form(@work)
        check_for_stale_update(@work, params)
        if WorkCompareService.update_work(work: @work, update_params:, current_user:)
          if params[:save_only] == "true"
            # Make sure we render the updated data
            prepare_decorators_for_work_form(@work)
            render view_name
          else
            redirect_to redirect_url
          end
        else
          # return 200 so the loadbalancer doesn't capture the error
          render view_name
        end
      end
    end
    # rubocop:enable Metrics/MethodLength

    def load_work
      @work = Work.find(params[:id])
    end

    # @note No testing coverage but not a route, not called
    def patch_params
      return {} unless params.key?(:patch)

      params[:patch]
    end

    # @note No testing coverage but not a route, not called
    def pre_curation_uploads_param
      return if patch_params.nil?

      patch_params[:pre_curation_uploads]
    end

    def deleted_files_param
      deleted_count = (params.dig("work", "deleted_files_count") || "0").to_i
      (1..deleted_count).map { |i| params.dig("work", "deleted_file_#{i}") }.select(&:present?)
    end

    # @note No testing coverage but not a route, not called
    def readme_file_param
      return if patch_params.nil?

      patch_params[:readme_file]
    end

    def rescue_aasm_error
      super
    rescue StandardError => generic_error
      redirect_to root_url, notice: "We apologize, an error was encountered: #{generic_error.message}. Please contact the PDC Describe administrators."
    end

    def redirect_aasm_error(transition_error_message)
      if @work.persisted?
        redirect_to edit_work_wizard_path(id: @work.id), notice: transition_error_message, params:
      else
        redirect_to work_create_new_submission_path(@work), notice: transition_error_message, params:
      end
    end
end

app/views/works_wizard/_form_wizard.html.erb
<%= render '/works/form_errors' %>

<!--
  Information about Bootstrap tabs
  https://getbootstrap.com/docs/5.0/components/navs-tabs/
  https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior
-->
<div class="d-flex align-items-start">

<%= render  partial: '/works/form_nav', locals:  { additional_selected: false, required_selected: true,
                                                   additional_button_class: "", required_button_class: "show active" } %>

  <div>
    <%= form_with(model: @work, url: update_work_wizard_path(@work), class: ["work-form"], data: { work: @work.form_attributes }) do |form| %>
      <%= render partial: '/works/form_metadata', locals:  { form: form, required_class: "show active", additional_class: "" } %>

      <hr />
      <div class="actions">
        <%= link_to 'Cancel', user_path(current_user), class: "btn btn-secondary" %>

        <%= form.submit "Next", class: "btn btn-primary wizard-next-button", id: "btn-submit" %>
        <%= form.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      </div>

      <%= render '/works/form_hidden_fields' %>
    <% end %>
  </div>
</div>

app/views/works_wizard/_wizard_progress.html.erb
<div style="height: 27px">
  <div style="float: right;">
    <div class="wizard-progress">
      <div class="wizard-step">
        <span class="wizard-step-info">Describe</span><br>
        <span class="wizard-step-bar<%= wizard_step == 1 ? '-active' : '' %>">&nbsp;</span>
      </div>
      <div class="wizard-step">
        <span class="wizard-step-info">Readme</span><br>
        <span class="wizard-step-bar<%= wizard_step == 2 ? '-active' : '' %>">&nbsp;</span>
      </div>
      <div class="wizard-step">
        <span class="wizard-step-info">Upload</span><br>
        <span class="wizard-step-bar<%= wizard_step == 3 ? '-active' : '' %>">&nbsp;</span>
      </div>
      <div class="wizard-step">
        <span class="wizard-step-info">Review</span><br>
        <span class="wizard-step-bar<%= wizard_step == 4 ? '-active' : '' %>">&nbsp;</span>
      </div>
      <div class="wizard-step">
        <span class="wizard-step-info">Completed</span><br>
        <span class="wizard-step-bar<%= wizard_step == 5 ? '-active' : '' %>">&nbsp;</span>
      </div>
    </div>
  </div>
</div>
<hr>

app/views/works_wizard/attachment_select.html.erb
<div class="wizard-area">
  <h1>New Submission (<%= @work.title %>)</h1>
  <%= render "wizard_progress", wizard_step: 3 %>
  <p>PDC can accommodate submissions of all sizes, but please be aware that <%= link_to "large data submissions", "https://researchdata.princeton.edu/research-lifecycle-guide/publishing-large-datasets", target: "_blank" %> usually take more time and may require assistance from PRDS staff, and <%= link_to "very large submissions may have costs associated", "https://drive.google.com/file/d/1GECvKoOjwqvKTKYvyNThCyzTWjD6cPxs/view", target: "_blank" %>. If you have any questions, please contact <%= link_to "prds@princeton.edu", "mailto:prds@princeton.edu" %> before proceeding.</p>
  <p>Begin the process to upload your submission. Please select the most appropriate description.</p>

  <p>My submission is...</p>
  <%= form_with(model: @work, url: work_attachment_selected_path(@work)) do |form| %>
    <input type="radio" id="attachment_type" name="attachment_type" value="file_upload" class="wizard-radio-button"
      <%= @work.files_location_upload? ? "checked" : "" %>>under 100MB and I want to upload the files directly.</input><br/>

    <input type="radio" id="attachment_type" name="attachment_type" value="file_other" class="wizard-radio-button"
      <%= @work.files_location_other? ? "checked" : "" %>>more than 100MB or I am unable to upload.</input><br/>

    <div class="actions">
      <%= submit_tag "Next", class: "btn btn-primary wizard-next-button" %>
      <%= form.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      <%= link_to "Previous", work_readme_select_path(@work, wizard: true), class: "btn btn-previous wizard-next-button" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/works_wizard/edit_wizard.html.erb
<div class="wizard-area">
  <h1>New Submission</h1>
  <%= render "wizard_progress", wizard_step: 1 %>
  <%= render partial: 'form_wizard', locals: { form_submit_url: update_work_wizard_path(@work),
                                               additional_selected: false, required_selected: true,
                                               required_class: "show active", additional_class: ""} %>
</div>

<%= javascript_include_tag 'edit_work_utils' %>

app/views/works_wizard/file_other.html.erb
<div class="wizard-area">
  <h1>New Submission (<%= @work.title %>)</h1>
  <%= render "wizard_progress", wizard_step: 3 %>
  <p>If your submission is over 100MB or you had trouble uploading, <%= link_to "we support data transfers via Globus", "https://researchdata.princeton.edu/research-lifecycle-guide/publishing-large-datasets", target: "_blank" %>.
  After you complete this form, the team will send you further instructions and guide you as needed.
  If you don't already have a Globus account linked to your Princeton credentials, you will also need to
  <%= link_to "log into Globus and select Princeton as your existing organization", "https://docs.globus.org/guides/tutorials/manage-files/transfer-files/", target: "_blank" %>.
  For now, please indicate where your files are currently stored, approximately how many files you have,
  the total size of your submission, and whether you have a specific deadline to meet.</p>

  <%= form_with(model: @work, url: work_review_path(@work)) do |form| %>
    <textarea id="location_notes" name="location_notes"cols="80", rows="10"
      placeholder="Where and how we may access your files"><%= @work.location_notes %></textarea>
    <div class="actions">
      <%= submit_tag "Next", class: "btn btn-primary wizard-next-button" %>
      <%= form.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      <%= link_to "Previous", work_attachment_select_url(@work, wizard: true), class: "btn btn-previous wizard-next-button" %>
    </div>
  <% end %>
</div>

app/views/works_wizard/file_upload.html.erb
<div class="wizard-area">
  <h1><%= t('works.form.file_upload.heading', work_title: @work.title) %></h1>
  <%= render "wizard_progress", wizard_step: 3 %>
  <%= form_with(model: @work, scope: :patch, url: work_file_uploaded_path(id: @work.id), class: ["work-form"]) do |f| %>
    <div id="file-error" class="error_box"></div>

    <div class="deposit-uploads">
      <section class="uploads">
        <h2 class="h2"><%= t('works.uploads.post_curation.heading') %></h2>
        <%= render(partial: 'works/s3_resources', locals: { edit_mode: true, form: f, wizard_mode: true }) %>
      </section>
      <div class="container-fluid deposit-uploads">
        <span id="uppy_upload_url" class="hidden"><%= work_wizard_upload_files_path(@work) %></span>
        <div id="file-upload-area"></div>
        <button id="add-files-button" class="btn btn-secondary" style="width: 200px;"><i class="bi bi-plus-circle"></i> Add Files</button>
        <div id="file-error" class="error_box"></div>
      </div>
    </div>

    <p><%= t('works.form.file_upload.actions') %></p>
    <div class="actions">
      <%= f.submit(t('works.form.file_upload.continue'), class: "btn btn-primary wizard-next-button", id: 'file-upload') %>
      <%= f.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      <%= link_to t('works.form.file_upload.go_back'), work_attachment_select_url(@work, wizard: true), class: "btn btn-previous wizard-next-button" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-secondary" %>
    </div>

    <!-- tracks deleted files count, notice that this field is hidden -->
    <input type="text" id="deleted_files_count" name="work[deleted_files_count]" value="0" class="hidden" />
  <% end %>
</div>

<!-- Provides the JavaScript to handle delete files functionality. -->
<%= javascript_include_tag 'edit_work_utils' %>

app/views/works_wizard/new_submission.html.erb
<style>
  p {
    font-size: larger;
  }

  .input-text-long {
    width: 700px;
  }

  .input-text-year {
    width: 70px;
  }

  .section-title {
    padding-top: 20px;
  }

  .doi-text {
    font-size: large;
    font-style: italic;
  }

  .add-title-button {
    color: #0c68f0;
    font-weight: bold;
    font-size: 22px;
  }
</style>

<div class="wizard-area">

  <!--
    In theory the new submission should never submit without a title or creators, because the javascript should prevent it.
    In reality we are occasionally having issues with the javascript failing and the button submitting anyway.
    In that case we want to show the error to the user so they can fix it. -->
  <%= render '/works/form_errors' %>

  <h1>New Submission</h1>
  <%= render "wizard_progress", wizard_step: 0 %>

  <p>
    You are starting a new submission.
  </p>
  <p>
    Before you proceed, please <b>review the PDC policies</b> for <%= link_to "Acceptance and Retention", "https://drive.google.com/file/d/1GECvKoOjwqvKTKYvyNThCyzTWjD6cPxs/view", target: "_blank" %> and <%= link_to "Distribution", "https://drive.google.com/file/d/1E8EgfyL2yB2rH0xCIIqYrTFE0QfY8Sk_/view", target: "_blank" %> to be sure your 
    intended submission is eligible for PDC, that you are authorized to grant permission for redistribution, and that you are prepared to 
    pay any applicable costs. If you are unsure about any of these points, please <%= link_to "reach out to our team", "mailto:prds@princeton.edu" %> before submitting.
  </p>
  <p>
    By clicking on the "Create New" button, a draft DOI will be reserved for this deposit.
  </p>

  <p>
    If you have already started a submission for this deposit, then please
    <a href="<%= user_path(current_user) %>">go to your dashboard</a> and complete
    the existing submission.
    You can find more documentation on the <%= link_to "PRDS Data Repository Help Page", "https://researchdata.princeton.edu/research-lifecycle-guide/princeton-research-data-repository", target: "_blank" %>.
    If you would like to talk to a specialist about
    your submission, we may be reached at <a href="mailto:prds@princeton.edu">prds@princeton.edu</a>.
  </p>

  <%= form_with(model: @work, url: work_new_submission_path) do |form| %>
    <%= render(partial: 'works/required_title', locals: {allow_many: false}) %>
    <%= render(partial: 'works/required_creators_table') %>
    <%= render '/works/form_hidden_fields' %>
    <hr />
    <div class="actions">
      <%= link_to "Cancel", work_delete_new_submission_path(@work), class: "btn btn-secondary" %>
      <%= submit_tag "Create New", class: "btn btn-primary wizard-next-button", id: "btn-create-new" %>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'edit_work_utils' %>

app/views/works_wizard/readme_select.html.erb
<div class="wizard-area">
  <h1><%= t('works.form.file_upload.heading', work_title: @work.title) %></h1>
  <%= render "wizard_progress", wizard_step: 2 %>
  <%= form_with(model: @work, scope: :patch, url: work_readme_uploaded_path(id: @work.id)) do |f| %>

    <h2>All submissions must include a README file. READMEs:</h2>
    <ul>
      <li>Are necessary so others can understand and use your data/code;</li>
      <li>Are plain text files (.txt);</li>
      <li>And contain background information including licensing/reuse information, a file manifest, file descriptions, instructions for data/software use, file versioning, file dependencies, etc.</li>
    </ul>

    <h2><%= t('works.form.readme_upload.title') %></h2>
    <p>If you have not created a README before, a <%= link_to("template may be found here","https://drive.google.com/file/d/1LCKPj9XxpwJeHYZV2kXROM79xbiBKnkp/view?usp=sharing", target: "blank") %>. See the PRDS website for more guidance on <%= link_to("how to create a README","https://researchdata.princeton.edu/research-lifecycle-guide/readmes-research-data", target: "blank") %>. </p>

    <p><%= t('works.form.readme_upload.actions') %></p>
    <div id="file-error" class="error_box"></div>
    <div class="file-upload">
      <span id="uppy_upload_url" class="hidden"><%= work_readme_uploaded_payload_path(@work) %></span>
      <div id="file-upload-area"></div>
      <% if @readme.present? %>
        <p id="new-readme"><b><%= @readme %></b> was previously uploaded. You will replace it if you select a different file. </p>
        <button id="add-readme" class="btn btn-secondary" style="width: 200px;"><i class="bi bi-plus-circle"></i> Replace README</button>
      <% else %>
        <p id="new-readme"></p>
        <button id="add-readme" class="btn btn-secondary" style="width: 200px;"><i class="bi bi-plus-circle"></i> Add README</button>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit(t('works.form.readme_upload.continue'), class: "btn btn-primary wizard-next-button", id: 'readme-upload', disabled: @readme.blank?) %>
      <%= f.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      <%= link_to 'Previous', work_update_additional_path(@work), class: "btn btn-previous wizard-next-button" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

<!-- Provides the JavaScript to handle add/replace readme. -->
<%= javascript_include_tag 'edit_work_utils' %>

app/views/works_wizard/review.html.erb
<div class="wizard-area">
  <h1>New Submission (<%= @work.title %>)</h1>
  <%= render "wizard_progress", wizard_step: 4 %>
  <%= render "/works/license_text" %>
  <p>Data curators will review the submission for accuracy and completeness to make
    it more discoverable and reusable. Recommendations will be available in the "unfinished submissions"
    section of this form within 5-10 business days.</p>

  <%= form_with(model: @work, url: work_validate_wizard_path(@work)) do |form| %>
    <textarea id="submission_notes" name="submission_notes" cols="80", rows="10"
      placeholder="(optional) Type here to leave a message for the curators"><%= @work.submission_notes %></textarea>
    <div class="actions">
      <%= submit_tag "Grant License and Complete", class: "btn btn-primary wizard-next-button", id: "grant-button" %>
      <%= form.button 'Save', type: 'submit', name: 'save_only', value: 'true', class: "btn btn-save wizard-next-button" %>
      <%= link_to "Previous", file_location_url , class: "btn btn-previous wizard-next-button" %>
      <%= link_to "Cancel", user_path(current_user), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/works_wizard/update_additional.html.erb
<div class="wizard-area">
  <h1>New Submission</h1>
  <%= render "wizard_progress", wizard_step: 1 %>
  <%= render partial: 'form_wizard', locals: { form_submit_url: work_update_additional_path(@work),
                                               additional_selected: true, required_selected: false,
                                               required_class: "", additional_class: "show active"} %>
</div>

<%= javascript_include_tag 'edit_work_utils' %>